### ISSUE TITLE
Immediate Generation Breakdown

### ISSUE THREAD

**Issue by Luigi2898** [Luigi2898/Laboratori-ISA#48]
Immediate generation is not working properly. Simulating with [https://github.com/Luigi2898/Laboratori-ISA/blob/main/Lab3/code/alu_store.txt](link) happens that executing `srai` the shift amount is 1030 instead of 9.

**Comment by francescofalconieri** [comment]
Anyway, it's spelled breakdown.

**Comment by Luigi2898** [comment]
Dyslexia bring me away.

**Comment by francescofalconieri** [comment]
SRAI detection added to the component.
